package com.cognizant.cvs.poc.routing_rules;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class LineItem implements java.io.Serializable {

    static final long serialVersionUID = 1L;

	private java.lang.String id;

	private java.lang.String name;

	private java.lang.String orderId;

	private java.lang.String state;

    public java.lang.String getId() {
        return this.id;
    }
    
    public void setId(java.lang.String id) {
        this.id = id;
    }

    public java.lang.String getName() {
        return this.name;
    }
    
    public void setName(java.lang.String name) {
        this.name = name;
    }

    public java.lang.String getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(java.lang.String orderId) {
        this.orderId = orderId;
    }

    public java.lang.String getState() {
        return this.state;
    }
    
    public void setState(java.lang.String state) {
        this.state = state;
    }

	public LineItem() {
	}

	public LineItem(java.lang.String id, java.lang.String name,
			java.lang.String state, java.lang.String orderId) {
		this.id = id;
		this.name = name;
		this.state = state;
		this.orderId = orderId;
	}

	@Override
	public String toString() {
		return "LineItem [id=" + id + ", name=" + name + ", orderId=" + orderId + ", state=" + state + "]";
	}

	
	
}