package com.cognizant.cvs.poc.routing_rules;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Store implements java.io.Serializable {

    static final long serialVersionUID = 1L;

	private java.lang.String id;

	private java.util.List<com.cognizant.cvs.poc.routing_rules.Rph> pharmacists;

	private java.lang.String state;

	private boolean shortlisted;

	private java.lang.Integer availability;

	public java.lang.String getId() {
        return this.id;
    }
    
    public void setId(java.lang.String id) {
        this.id = id;
    }

    public java.util.List<com.cognizant.cvs.poc.routing_rules.Rph> getPharmacists() {
        return this.pharmacists;
    }
    
    public void setPharmacists(java.util.List<com.cognizant.cvs.poc.routing_rules.Rph> pharmacists) {
        this.pharmacists = pharmacists;
    }

    public java.lang.String getState() {
        return this.state;
    }
    
    public void setState(java.lang.String state) {
        this.state = state;
    }

	public boolean isShortlisted() {
		return this.shortlisted;
	}

	public void setShortlisted(boolean shortlisted) {
		this.shortlisted = shortlisted;
	}

	public java.lang.Integer getAvailability() {
		return this.availability;
	}

	public void setAvailability(java.lang.Integer availability) {
		this.availability = availability;
	}

	public Store() {
	}

	public Store(
			java.lang.String id,
			java.lang.String state,
			java.util.List<com.cognizant.cvs.poc.routing_rules.Rph> pharmacists,
			boolean shortlisted, java.lang.Integer availability) {
		this.id = id;
		this.state = state;
		this.pharmacists = pharmacists;
		this.shortlisted = shortlisted;
		this.availability = availability;
	}

	@Override
	public String toString() {
		return "Store [id=" + id + ", pharmacists=" + pharmacists + ", state=" + state + ", shortlisted=" + shortlisted
				+ ", availability=" + availability + "]";
	}
	
	

}