package com.redhat.gpte.policyquote;

import com.redhat.gpte.policyquote.model.Driver
import com.redhat.gpte.policyquote.model.Policy

rule "NewerVehicleSurcharge"

	no-loop 
	ruleflow-group "surcharge"
	lock-on-active 
    
    when
        //conditions
        $driver : Driver( $id : id)
        $policy : Policy(price > 0, policyType == "AUTO", driver == $id, vehicleYear >= 2004)
    then
        //actions
        modify($policy) {setPrice($policy.getPrice() + 100)};

end
