package com.redhat.gpte.policyquote;

import com.redhat.gpte.policyquote.model.Driver
import com.redhat.gpte.policyquote.model.Policy

rule "SafeYouths"

    ruleflow-group "calculation"

    when
        //conditions
        $driver : Driver(age >= 18 && < 25, numberOfAccidents < 1, numberOfTickets <= 1, $id : id)
        $policy : Policy(price == 0, policyType == "AUTO", driver == $id)
    then
        //actions
        modify($policy) {setPrice(450)};
        
end


