package com.redhat.gpte.policyquote;

import com.redhat.gpte.policyquote.model.Driver
import com.redhat.gpte.policyquote.model.Policy

rule "SafeAdults"

    ruleflow-group "calculation"

    when
        $driver : Driver(age > 24, numberOfAccidents < 1, numberOfTickets <= 1, $id : id)
        $policy : Policy(price == 0, policyType == "AUTO", driver == $id)
    then
        //actions
        modify($policy) {setPrice(120)};
        
end

